timezone: Asia/Shanghai

ai:
  ai_type: openai
  api_key: sk-proj-xxxx
  model: "gpt-4"
  temperature: 0.7

rss:
  - name: elonmusk
    url: http://127.0.0.1:8080
    type: nitter
    enable: true
    description: ""
    others:
      author: "elonmusk"
      public_url: https://x.com
    notify:
      - "matrix-1"

  - name: test
    url: https://rss.arxiv.org/atom/quant-ph
    enable: true
    notify:
      - matrix-1

notify:
  - name: matrix-1
    type: matrix
    username: "@rssbot:example.com"
    token: "9k8wPlccccgCBXDwJO0="
    homeserver: https://matrix.example.com
    room_id: "!xxxxx:example.com"

  - name: matrix-2
    type: matrix
    username: "@rssbot:example.com"
    token: "9k8wPlsfffffXDwJO0="
    homeserver: https://matrix.example.com
    room_id: "!xxxx:example.com"
