# you can use this file as an example to create your own config.yaml
# copy this file to config.yaml and edit it

# config the timezone, if None it will use the system timezone
timezone: Asia/Shanghai

# if you want to append the timezone to the message
other_tz:
  New_York: "America/New_York"
  Chicago: "America/Chicago"

translate_to: Chinese # If not None, it will add prompts to translate the AI response to this language

log:
  level: info
  file: /tmp/rss/logs
  to_console: true

ai:
  ai_type: openai
  api_key: sk-proj-xxxx
  model: "gpt-4"
  temperature: 0.7

rss:
  - name: elonmusk
    url: http://127.0.0.1:8080
    # type can be rss, nitter(I use nitter to get the rss feed of x.com)
    type: nitter
    enable: true
    description: ""
    others:
      author: "elonmusk"
      public_url: https://x.com
    # specify the notifications whiich you define at 'notify' section
    # you can define multiple notifications
    notify:
      - matrix-1 # Send the summary to the notify whose name is 'matrix-1' at the 'notify' section

  - name: test
    url: https://rss.arxiv.org/atom/quant-ph
    enable: true
    # you can add your own prompts for this RSS feed to AI
    prompts: ""
    notify:
      - matrix-1 # Send the summary to the notify whose name is 'matrix-1' at the 'notify' section

notify:
  - name: matrix-1
    type: matrix
    username: "@rssbot:example.com"
    token: "9k8wPlccccgCBXDwJO0="
    homeserver: https://matrix.example.com
    room_id: "!xxxxx:example.com"

  - name: matrix-2
    type: matrix
    username: "@rssbot:example.com"
    token: "9k8wPlsfffffXDwJO0="
    homeserver: https://matrix.example.com
    room_id: "!xxxx:example.com"
